config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'categories/new', as: 'categories_new'
  get 'categories/:id', to: 'categories#show'
  get 'categories/:id/edit', to: 'categories#edit'
  post 'categories', to: 'categories#create'
  delete 'categories/:id', to: 'categories#destroy'
  patch 'categories/:id', to: 'categories#update', as: 'update_category'
  get 'categories', to: 'categories#index'

  resources :menus
  get '', to: 'menus#index'
  get 'menus', to: 'menus#index'
  get 'menus/new', to: 'menus#new'
  post 'menus', to: 'menus#create'
  delete 'menus/:id', to: 'menus#destroy'
  get 'menus/:id', to: 'menus#show'
  get 'menus/:id/edit', to: 'menus#edit'
  patch 'menus/:id', to: 'menus#update', as: 'update_menu'

  resources :customers
  get 'customers', to: 'customers#index'
  get 'customers/new', to: 'customers#new'
  post 'customers', to: 'customers#create'
  delete 'customers/:id', to: 'customers#destroy'
  get 'customers/:id', to: 'customers#show'
  get 'customers/:id/edit', to: 'customers#edit'
  patch 'customers/:id', to: 'customers#update', as: 'update_customers'

  resources :orders
  get 'orders', to: 'orders#index'
  get 'orders/new', to: 'orders#new'
  get 'orders/new/:id', to: 'orders#new_by_customer', as: 'get_order_customer'
  post 'orders/:id', to: 'orders#create'
  delete 'orders/:id', to: 'orders#destroy'
  get 'orders/:id', to: 'orders#show'
  get 'orders/:id/edit', to: 'orders#edit'
  patch 'orders/:id', to: 'orders#update', as: 'update_orders'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/menu.rb
class Menu < ApplicationRecord
    has_many :menu_orders, dependent: :destroy
    has_and_belongs_to_many :categories
    accepts_nested_attributes_for :categories
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
    def index
      if params[:search].nil?
        @menus = Menu.all
      else
        @parameter = params[:search].downcase  
        @menus = Menu.where("lower(menu_name) LIKE :search", search: "%#{@parameter}%")  

        if @menus.blank? 
          @parameter = params[:search].downcase  
          @categories = Category.where("lower(name) LIKE :search", search: "%#{@parameter}%")
  
          id = []
          @categories.each do |category|
            id.push(category.id)
          end
  
          menu_result = ActiveRecord::Base.connection.execute("SELECT menu_id FROM categories_menus where categories_menus.category_id in (#{id.join(",")})")
  
          @menus = []
          menu_result.each do |result|
            @menus.push(Menu.find(result["menu_id"]))
          end
        end
      end
    end

    def new
        @menu = Menu.new
    end

    def show
      @menu = Menu.find(params[:id])
    end

    def edit
      @menu = Menu.find(params[:id])
    end

    def destroy
      @menu = Menu.find(params[:id])
      @menu.destroy
  
      redirect_to action: :index
    end

    def update
      @menu = Menu.find(params[:id])
  
      if @menu.update(menu_params)
        redirect_to action: :index
      else
        flash[:error] = @menu.errors.full_messages.[](0)
        render :edit
      end
    end

    def create
        @menu = Menu.new(menu_params)
        p @menu.category_ids
        if @menu.save
          flash[:success] = "Menu created successfully."
          redirect_to action: :index
        else
          flash[:error] = @category.errors.full_messages.[](0)
          render action: :new
        end
      end

    private
    def menu_params
      params.require(:menu).permit(:menu_name, :price, category_ids: [])
    end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/edit.html.erb
<div class="border-2 border-gray-300 p-4">
<h1 class="text-2xl">Edit menu items</h1>
<hr class="mb-4" />

<%= form_for @menu, url: {action: "update"}, html: {class: "flex flex-col"} do |f| %>
  <%= f.label :menu_name, "Menu Name: " %>
  <%= f.text_field :menu_name, class: 'border-2 border-gray-200 rounded-md focus:ring-2 focus:ring-blue-600 w-full my-4 h-8 px-2' %>

  <%= f.label :price, "Price: " %>
  <%= f.text_field :price, class: 'border-2 border-gray-200 rounded-md focus:ring-2 focus:ring-blue-600 w-full mt-4 h-8 px-2' %>

  <%= f.label :category_ids, "Category: ", class: 'my-4' %>
  <%= collection_check_boxes(:menu, :category_ids, Category.all, :id, :name, include_hidden: false) do |checkbox| %>
      <div class="mb-1">
        <%= checkbox.check_box %>
        <%= checkbox.label %> 
      </div>
  <% end %>
  <div class="flex flex-row self-end mt-16">
  <%= link_to "Cancel", :menus, class: "bg-gray-400 text-white p-2 rounded-md" %>
  <%= f.submit "Submit Menu", class: 'bg-green-500 active:bg-green-700 cursor-pointer text-white p-2 rounded-md ml-4' %>
  </div>
<% end %>

</div>

app/views/menus/index.html.erb
<div class="flex flex-row justify-between items-center">
<h1 class="text-xl font-bold">Menu Items</h1>
  <%= link_to "Add Menu Items", :new_menu, class: "bg-blue-500 text-white mb-2 p-2 rounded-md" %>
</div>

<%= form_with url: "/menus",  class: 'mb-4', method: :get do |form| %>
  <%= form.label :search, "Search for:" %>
  <%= form.text_field :search, class: 'border-2 border-gray-200 rounded-md focus:ring-2 focus:ring-blue-600 w-full my-4 h-8 px-2' %>
  <%= form.submit "Search", class: 'bg-green-500 active:bg-green-700 cursor-pointer text-white p-2 rounded-md'%>
<% end %>

<table class="table-fixed w-full">
  <thead>
    <tr>
      <th class="w-1/12 border-gray-400 border-2">No</th>
      <th class="w-1/2 border-gray-400 border-2">Menu Name</th>
      <th class="w-1/4 border-gray-400 border-2">Price</th>
      <th class="w-1/4 border-gray-400 border-2">Category</th>
      <th class="w-1/4 border-gray-400 border-2">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each.with_index do |menu, index| %>
      <tr>
        <td class="border-gray-400 border-2 text-center"><%= index + 1 %></td>
        <td class="border-gray-400 border-2 px-2"><%= menu.menu_name %></td>
        <td class="border-gray-400 border-2 px-2"><%= menu.price %></td>
        <td class="border-gray-400 border-2 pl-8">
        <ul class="list-disc">
          <% menu.category_ids.each do |id| %>
            <li><%= Category.find(id).name %></li>
          <% end %>
        </ul>
        </td>
        </td>
        <td class="border-gray-400 border-r-2 border-b-2 flex flex-col px-32">
            <%= link_to "View", menu_path(menu, @menu), class: "bg-green-500 text-white mt-2 mb-2 p-2 rounded-md text-center" %>
            <%= link_to "Edit",  edit_menu_path(menu, @menu), class: "bg-blue-500 text-white mt-2 mb-2 p-2 rounded-md text-center" %>
            <%= link_to "Delete", menu_path(menu, @menu), method: :delete, class: "bg-red-500 text-white mt-2 mb-2 p-2 rounded-md text-center" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/menus/new.html.erb
<div class="border-2 border-gray-300 p-4">
<h1 class="text-2xl">Add menu items</h1>
<hr class="mb-4" />

<%= form_for @menu, url: {action: "create"}, html: {class: "flex flex-col"} do |f| %>
  <%= f.label :menu_name, "Menu Name: " %>
  <%= f.text_field :menu_name, class: 'border-2 border-gray-200 rounded-md focus:ring-2 focus:ring-blue-600 w-full my-4 h-8 px-2' %>

  <%= f.label :price, "Price: " %>
  <%= f.text_field :price, class: 'border-2 border-gray-200 rounded-md focus:ring-2 focus:ring-blue-600 w-full mt-4 h-8 px-2' %>

  <%= f.label :category_ids, "Category: ", class: 'my-4' %>
  <%= collection_check_boxes(:menu, :category_ids, Category.all, :id, :name, include_hidden: false) do |checkbox| %>
      <div class="mb-1">
        <%= checkbox.check_box %>
        <%= checkbox.label %> 
      </div>
  <% end %>
  <div class="flex flex-row self-end mt-16">
  <%= link_to "Cancel", :menus, class: "bg-gray-400 text-white p-2 rounded-md" %>
  <%= f.submit "Submit Menu", class: 'bg-green-500 active:bg-green-700 cursor-pointer text-white p-2 rounded-md ml-4' %>
  </div>
<% end %>

</div>

app/views/menus/show.html.erb
<div class="border-2 border-gray-300 p-4">
<div class="flex flex-row justify-between">
<h1 class="text-2xl">Menu Item</h1>
<%= link_to "Back", :menus, class: "bg-gray-400 text-white p-2 rounded-md" %>
</div>
<hr class="mb-4" />

<%= form_for @menu, html: {class: "flex flex-col"} do |f| %>
  <%= f.label :menu_name, "Menu Name: " %>
  <%= f.text_field :menu_name, :disabled => true, class: 'border-2 border-gray-200 rounded-md focus:ring-2 focus:ring-blue-600 w-full my-4 h-8 px-2' %>

  <%= f.label :price, "Price: " %>
  <%= f.text_field :price, :disabled => true, class: 'border-2 border-gray-200 rounded-md focus:ring-2 focus:ring-blue-600 w-full mt-4 h-8 px-2' %>

  <%= f.label :category_ids, "Category: ", class: 'my-4' %>
  <%= collection_check_boxes(:menu, :category_ids, Category.all, :id, :name, include_hidden: false) do |checkbox| %>
      <div class="mb-1">
        <%= checkbox.check_box :disabled => true %>
        <%= checkbox.label %> 
      </div>
  <% end %>
  <div class="flex flex-row self-end mt-16">
  <%= link_to "Delete", menu_path(@menu), method: :delete, class: "bg-red-500 text-white p-2 rounded-md" %>
  <%= link_to "Edit", edit_menu_path(@menu), class: "w-16 bg-blue-500 text-white p-2 rounded-md ml-4 text-center" %>
  </div>
<% end %>

</div>