config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'categories/new', as: 'categories_new'
  get 'categories/:id', to: 'categories#show'
  get 'categories/:id/edit', to: 'categories#edit'
  post 'categories', to: 'categories#create'
  delete 'categories/:id', to: 'categories#destroy'
  patch 'categories/:id', to: 'categories#update', as: 'update_category'
  get 'categories', to: 'categories#index'

  resources :menus
  get '', to: 'menus#index'
  get 'menus', to: 'menus#index'
  get 'menus/new', to: 'menus#new'
  post 'menus', to: 'menus#create'
  delete 'menus/:id', to: 'menus#destroy'
  get 'menus/:id', to: 'menus#show'
  get 'menus/:id/edit', to: 'menus#edit'
  patch 'menus/:id', to: 'menus#update', as: 'update_menu'

  resources :customers
  get 'customers', to: 'customers#index'
  get 'customers/new', to: 'customers#new'
  post 'customers', to: 'customers#create'
  delete 'customers/:id', to: 'customers#destroy'
  get 'customers/:id', to: 'customers#show'
  get 'customers/:id/edit', to: 'customers#edit'
  patch 'customers/:id', to: 'customers#update', as: 'update_customers'

  resources :orders
  get 'orders', to: 'orders#index'
  get 'orders/new', to: 'orders#new'
  get 'orders/new/:id', to: 'orders#new_by_customer', as: 'get_order_customer'
  post 'orders/:id', to: 'orders#create'
  delete 'orders/:id', to: 'orders#destroy'
  get 'orders/:id', to: 'orders#show'
  get 'orders/:id/edit', to: 'orders#edit'
  patch 'orders/:id', to: 'orders#update', as: 'update_orders'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    def new
        @customer = Customer.new
    end

    def edit
        @customer = Customer.find(params[:id])
    end

    def destroy
        @customer = Customer.find(params[:id])
        @customer.destroy

        redirect_to action: :index
    end

    def create
        @customer = Customer.new(customer_params)
        if @customer.save
          flash[:success] = "Customer created successfully."
          redirect_to action: :index
        else
          flash[:error] = @customer.errors.full_messages.[](0)
          render action: :new
        end
      end

    def update
        @customer = Customer.find(params[:id])

        if @customer.update(customer_params)
          redirect_to customers_path
        else
          flash[:error] = @customer.errors.full_messages.[](0)
          render :edit
        end
    end

    def show
        @customer = Customer.find(params[:id])
        @orders = Order.where(customer_id: params[:id])
    end

    def index
      if params[:search].nil?
        @customers = Customer.all
      else
        @parameter = params[:search].downcase  
        @customers = Customer.where("lower(customer_name) LIKE :search", search: "%#{@parameter}%")  
      end
    end

    private
    def customer_params
      params.require(:customer).permit(:customer_name, :phone_number)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<div class="border-2 border-gray-300 p-4">
<h1 class="text-2xl">Edit Customer</h1>
<hr class="mb-4" />

<%= form_for @customer, url: {action: "update"}, html: {class: "flex flex-col"} do |f| %>
  <%= f.label :customer_name, "Customer Name: " %>
  <%= f.text_field :customer_name, class: 'border-2 border-gray-200 rounded-md focus:ring-2 focus:ring-blue-600 w-full my-4 h-8 px-2' %>

  <%= f.label :phone_number, "Phone Number: " %>
  <%= f.text_field :phone_number, class: 'border-2 border-gray-200 rounded-md focus:ring-2 focus:ring-blue-600 w-full mt-4 h-8 px-2' %>

  <div class="flex flex-row self-end mt-16">
  <%= link_to "Cancel", :customers, class: "bg-gray-400 text-white p-2 rounded-md" %>
  <%= f.submit "Submit Menu", class: 'bg-green-500 active:bg-green-700 cursor-pointer text-white p-2 rounded-md ml-4' %>
  </div>
<% end %>

</div>

app/views/customers/index.html.erb
<div class="flex flex-row justify-between items-center">
<h1 class="text-xl font-bold">Customers</h1>
  <%= link_to "Add Customer", :new_customer, class: "bg-blue-500 text-white mb-2 p-2 rounded-md" %>
</div>

<%= form_with url: "/customers",  class: 'mb-4', method: :get do |form| %>
  <%= form.label :search, "Search for:" %>
  <%= form.text_field :search, class: 'border-2 border-gray-200 rounded-md focus:ring-2 focus:ring-blue-600 w-full my-4 h-8 px-2' %>
  <%= form.submit "Search", class: 'bg-green-500 active:bg-green-700 cursor-pointer text-white p-2 rounded-md'%>
<% end %>

<table class="table-fixed w-full">
  <thead>
    <tr>
      <th class="w-1/12 border-gray-400 border-2">No</th>
      <th class="w-1/2 border-gray-400 border-2">Customer Name</th>
      <th class="w-1/4 border-gray-400 border-2">Phone Number</th>
      <th class="w-1/4 border-gray-400 border-2">Action</th>
    </tr>
  </thead>

    <tbody>
    <% @customers.each.with_index do |customer, index| %>
      <tr>
        <td class="border-gray-400 border-2 text-center"><%= index + 1 %></td>
        <td class="border-gray-400 border-2 px-2"><%= customer.customer_name %></td>
        <td class="border-gray-400 border-2 px-2"><%= customer.phone_number %></td>
        <td class="border-gray-400 border-r-2 border-b-2 flex flex-col px-32">
            <%= link_to "View" , customer_path(customer, @customer), class: "bg-green-500 text-white mt-2 mb-2 p-2 rounded-md text-center" %>
            <%= link_to "Edit", edit_customer_path(customer, @customer) , class: "bg-blue-500 text-white mt-2 mb-2 p-2 rounded-md text-center" %>
            <%= link_to "Delete", customer_path(customer, @customer), method: :delete, class: "bg-red-500 text-white mt-2 mb-2 p-2 rounded-md text-center" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/new.html.erb
<div class="border-2 border-gray-300 p-4">
<h1 class="text-2xl">Add Customer</h1>
<hr class="mb-4" />

<%= form_for @customer, url: {action: "create"}, html: {class: "flex flex-col"} do |f| %>
  <%= f.label :customer_name, "Customer Name: " %>
  <%= f.text_field :customer_name, class: 'border-2 border-gray-200 rounded-md focus:ring-2 focus:ring-blue-600 w-full my-4 h-8 px-2' %>

  <%= f.label :phone_number, "Phone Number: " %>
  <%= f.text_field :phone_number, class: 'border-2 border-gray-200 rounded-md focus:ring-2 focus:ring-blue-600 w-full mt-4 h-8 px-2' %>

  <div class="flex flex-row self-end mt-16">
  <%= link_to "Cancel", :customers, class: "bg-gray-400 text-white p-2 rounded-md" %>
  <%= f.submit "Submit Menu", class: 'bg-green-500 active:bg-green-700 cursor-pointer text-white p-2 rounded-md ml-4' %>
  </div>
<% end %>

</div>

app/views/customers/show.html.erb
<div class="border-2 border-gray-300 p-4">
<div class="flex flex-row justify-between">
<h1 class="text-2xl">Customer</h1>
<%= link_to "Back", :customers, class: "bg-gray-400 text-white p-2 rounded-md" %>
</div>
<hr class="mb-4" />

<%= form_for @customer, url: {action: "create"}, html: {class: "flex flex-col"} do |f| %>
  <%= f.label :customer_name, "Customer Name: " %>
  <%= f.text_field :customer_name, :disabled => true, class: 'border-2 border-gray-200 rounded-md focus:ring-2 focus:ring-blue-600 w-full my-4 h-8 px-2' %>

  <%= f.label :phone_number, "Phone Number: " %>
  <%= f.text_field :phone_number, :disabled => true, class: 'border-2 border-gray-200 rounded-md focus:ring-2 focus:ring-blue-600 w-full mt-4 h-8 px-2' %>

  <label class="mt-4">Orders</label>

  <table class="table-fixed w-full mt-4">
  <thead>
    <tr>
      <th class="w-1/12 border-gray-400 border-2">No</th>
      <th class="w-1/4 border-gray-400 border-2">Order ID</th>
      <th class="w-1/4 border-gray-400 border-2">Total Price</th>
      <th class="w-1/4 border-gray-400 border-2">Time created</th>
      <th class="w-1/4 border-gray-400 border-2">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each.with_index do |order, index| %>
      <tr>
        <td class="border-gray-400 border-2 text-center"><%= index + 1 %></td>
        <td class="border-gray-400 border-2 pl-8"><%= order.id %></td>
        <td class="border-gray-400 border-2 pl-8"><%= order.total_price %></td>
        <td class="border-gray-400 border-2 pl-8"><%= order.created_at.localtime.strftime("%e %B %Y, %T") %></td>
        <td class="border-gray-400 border-r-2 border-b-2 flex flex-col px-32">
            <%= link_to "View", order_path(order, @order), class: "bg-green-500 text-white mt-2 mb-2 p-2 rounded-md text-center" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

  <div class="flex flex-row self-end mt-16">
  <%= link_to "Delete", customer_path(@customer), method: :delete, class: "bg-red-500 text-white p-2 rounded-md" %>
  <%= link_to "Edit", edit_customer_path(@customer), class: "w-16 bg-blue-500 text-white p-2 rounded-md ml-4 text-center" %>
  </div>
<% end %>

</div>