config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'categories/new', as: 'categories_new'
  get 'categories/:id', to: 'categories#show'
  get 'categories/:id/edit', to: 'categories#edit'
  post 'categories', to: 'categories#create'
  delete 'categories/:id', to: 'categories#destroy'
  patch 'categories/:id', to: 'categories#update', as: 'update_category'
  get 'categories', to: 'categories#index'

  resources :menus
  get '', to: 'menus#index'
  get 'menus', to: 'menus#index'
  get 'menus/new', to: 'menus#new'
  post 'menus', to: 'menus#create'
  delete 'menus/:id', to: 'menus#destroy'
  get 'menus/:id', to: 'menus#show'
  get 'menus/:id/edit', to: 'menus#edit'
  patch 'menus/:id', to: 'menus#update', as: 'update_menu'

  resources :customers
  get 'customers', to: 'customers#index'
  get 'customers/new', to: 'customers#new'
  post 'customers', to: 'customers#create'
  delete 'customers/:id', to: 'customers#destroy'
  get 'customers/:id', to: 'customers#show'
  get 'customers/:id/edit', to: 'customers#edit'
  patch 'customers/:id', to: 'customers#update', as: 'update_customers'

  resources :orders
  get 'orders', to: 'orders#index'
  get 'orders/new', to: 'orders#new'
  get 'orders/new/:id', to: 'orders#new_by_customer', as: 'get_order_customer'
  post 'orders/:id', to: 'orders#create'
  delete 'orders/:id', to: 'orders#destroy'
  get 'orders/:id', to: 'orders#show'
  get 'orders/:id/edit', to: 'orders#edit'
  patch 'orders/:id', to: 'orders#update', as: 'update_orders'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :menu_orders, dependent: :destroy
    accepts_nested_attributes_for :menu_orders
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def index
      if params[:search].nil?
        @orders = Order.all
      else
        @parameter = params[:search].downcase  
        @customer = Customer.where("lower(customer_name) LIKE :search", search: "%#{@parameter}%").first

        if @customer.blank?
          @orders = []
        else
          @orders = Order.where(customer_id: @customer.id)
        end
      end
    end

    def new
      @customers = Customer.all
    end
    
    def new_by_customer
        @menus = Menu.all
        @order = Order.new
        @order.menu_orders.build
    end

    def show
      @order = Order.find(params[:id])
      @customer = Customer.find(@order.customer_id)
      @menu_orders = MenuOrder.where(order_id: @order.id)
    end

    def edit
      @order = Order.find(params[:id])
    end

    def destroy
      @order = Order.find(params[:id])
      @order.destroy
  
      redirect_to action: :index
    end

    def update
      @order = Order.find(params[:id])
  
      if @order.update(order_params)
        redirect_to action: :index
      else
        flash[:error] = @order.errors.full_messages.[](0)
        render :edit
      end
    end

    def create
      sum = 0
      params[:order][:menu_orders_attributes].each do |menu|
        sum += (Menu.find(menu.[](1)[:menu_id]).price.to_i * menu.[](1)[:quantity].to_i)
      end

      @order = Order.new(customer_id: params[:id], total_price: sum)

      if @order.save
        params[:order][:menu_orders_attributes].each do |menu|
          if !menu.[](1)[:quantity].blank? && menu.[](1)[:quantity] != "0"
            MenuOrder.create(menu_id: menu.[](1)[:menu_id], quantity: menu.[](1)[:quantity], order_id: @order.id)
          end
        end
        flash[:success] = "Order created successfully."
        redirect_to action: :index
      else
        flash[:error] = @order.errors.full_messages.[](0)
        render action: :new_by_customer
      end
    end

    private
    def order_params
      params.require(:order).permit(menu_orders_attributes: [:menu_id, :quantity])
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<div class="flex flex-row justify-between items-center">
<h1 class="text-xl font-bold">Orders</h1>
  <%= link_to "Add Order", :new_order, class: "bg-blue-500 text-white mb-2 p-2 rounded-md" %>
</div>

<%= form_with url: "/orders",  class: 'mb-4', method: :get do |form| %>
  <%= form.label :search, "Search for:" %>
  <%= form.text_field :search, class: 'border-2 border-gray-200 rounded-md focus:ring-2 focus:ring-blue-600 w-full my-4 h-8 px-2' %>
  <%= form.submit "Search", class: 'bg-green-500 active:bg-green-700 cursor-pointer text-white p-2 rounded-md'%>
<% end %>

<table class="table-fixed w-full">
  <thead>
    <tr>
      <th class="w-1/12 border-gray-400 border-2">No</th>
      <th class="w-1/4 border-gray-400 border-2">Customer Name</th>
      <th class="w-1/4 border-gray-400 border-2">Total Price</th>
      <th class="w-1/4 border-gray-400 border-2">Time created</th>
      <th class="w-1/4 border-gray-400 border-2">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each.with_index do |order, index| %>
      <tr>
        <td class="border-gray-400 border-2 text-center"><%= index + 1 %></td>
        <td class="border-gray-400 border-2 px-2"><%= Customer.find(order.customer_id).customer_name %></td>
        <td class="border-gray-400 border-2 pl-8"><%= order.total_price %></td>
        <td class="border-gray-400 border-2 pl-8"><%= order.created_at.localtime.strftime("%e %B %Y, %T") %></td>
        <td class="border-gray-400 border-r-2 border-b-2 flex flex-col px-32">
            <%= link_to "View", order_path(order, @order), class: "bg-green-500 text-white mt-2 mb-2 p-2 rounded-md text-center" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/new.html.erb
<div class="border-2 border-gray-300 p-4">
<h1 class="text-2xl">Add order</h1>
<hr class="mb-4" />

<div class="flex flex-col justify-center">

<table class="table-fixed w-full">
  <thead>
    <tr>
      <th class="w-1/12 border-gray-400 border-2">No</th>
      <th class="w-1/2 border-gray-400 border-2">Customer Name</th>
      <th class="w-1/4 border-gray-400 border-2">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each.with_index do |customer, index| %>
      <tr>
        <td class="border-gray-400 border-2 text-center"><%= index + 1 %></td>
        <td class="border-gray-400 border-2 px-2"><%= customer.customer_name %></td>
        <td class="border-gray-400 border-r-2 border-b-2 flex flex-col px-32">
          <%= link_to "Choose Menu", get_order_customer_path(customer, @customer), class: "bg-green-500 text-white mt-2 mb-2 p-2 rounded-md text-center" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
  <div class="flex flex-row self-end mt-16">
    <%= link_to "Cancel", :orders, class: "bg-gray-400 text-white p-2 rounded-md" %>
  </div>
</div>

app/views/orders/new_by_customer.html.erb
<div class="border-2 border-gray-300 p-4 h-96">
<h1 class="text-xl font-bold">Menu items</h1>
<hr class="mb-4" />
<%= form_with model: @order, url: "/orders/" << params[:id], class: 'flex flex-col', method: :post do |form| %>
<table class="table-fixed w-full">
  <thead>
    <tr>
      <th class="w-1/12 border-gray-400 border-2">No</th>
      <th class="w-1/2 border-gray-400 border-2">Menu Name</th>
      <th class="w-1/2 border-gray-400 border-2">Price</th>
      <th class="w-1/4 border-gray-400 border-2">Quantity</th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each.with_index do |menu, index| %>
      <tr>
        <td class="border-gray-400 border-2 text-center"><%= index + 1 %></td>
        <td class="border-gray-400 border-2 px-2"><%= menu.menu_name %></td>
        <td class="border-gray-400 border-2 px-2"><%= menu.price %></td>
        <td class="border-gray-400 border-r-2 border-b-2 flex flex-col p-4">
        <%= form.fields_for :menu_orders do |builder| %>
              <div class="field">
                <%= builder.hidden_field :menu_id, value: menu.id %>
                <%= builder.number_field :quantity, min: 0, class: 'border-2 border-gray-200 rounded-md focus:ring-2 focus:ring-blue-600 w-full h-8 px-2' %>
              </div>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
  <div class="flex flex-row self-end mt-16">
  <%= link_to "Cancel", :orders, class: "bg-gray-400 text-white p-2 rounded-md" %>
  <%= form.submit "Submit Order", class: 'bg-green-500 active:bg-green-700 cursor-pointer text-white p-2 rounded-md ml-4' %>
  </div>
<% end %>
</div>

app/views/orders/show.html.erb
<div class="border-2 border-gray-300 p-4">

<div class="flex flex-row justify-between">
<h1 class="text-2xl">Order</h1>
<%= link_to "Back", :orders, class: "bg-gray-400 text-white p-2 rounded-md" %>
</div>
<hr class="mb-4" />

<form class="flex flex-col">
    <label>Customer Name:</label>
    <input disabled class='border-2 border-gray-200 rounded-md focus:ring-2 focus:ring-blue-600 w-full my-4 h-8 px-2' value=<%= @customer.customer_name %>></input>
    <label>Total price:</label>
    <input disabled class='border-2 border-gray-200 rounded-md focus:ring-2 focus:ring-blue-600 w-full my-4 h-8 px-2' value=<%= @order.total_price %>></input>
</form>

<label>Detail:</label>
<table class="table-fixed w-full">
  <thead>
    <tr>
      <th class="w-1/12 border-gray-400 border-2">No</th>
      <th class="w-1/2 border-gray-400 border-2">Menu Name</th>
      <th class="w-1/4 border-gray-400 border-2">Menu Price</th>
      <th class="w-1/4 border-gray-400 border-2">Quantity</th>
      <th class="w-1/4 border-gray-400 border-2">Subtotal</th>
    </tr>
  </thead>

  <tbody>
    <% @menu_orders.each.with_index do |order, index| %>
      <tr>
        <td class="border-gray-400 border-2 text-center"><%= index + 1 %></td>
        <td class="border-gray-400 border-2 px-2"><%= Menu.find(order.menu_id).menu_name %></td>
        <td class="border-gray-400 border-2 px-2"><%= Menu.find(order.menu_id).price %></td>
        <td class="border-gray-400 border-2 pl-8"><%= order.quantity %></td>
        <td class="border-gray-400 border-2 px-2"><%= Menu.find(order.menu_id).price * order.quantity %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>