config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'categories/new', as: 'categories_new'
  get 'categories/:id', to: 'categories#show'
  get 'categories/:id/edit', to: 'categories#edit'
  post 'categories', to: 'categories#create'
  delete 'categories/:id', to: 'categories#destroy'
  patch 'categories/:id', to: 'categories#update', as: 'update_category'
  get 'categories', to: 'categories#index'

  resources :menus
  get '', to: 'menus#index'
  get 'menus', to: 'menus#index'
  get 'menus/new', to: 'menus#new'
  post 'menus', to: 'menus#create'
  delete 'menus/:id', to: 'menus#destroy'
  get 'menus/:id', to: 'menus#show'
  get 'menus/:id/edit', to: 'menus#edit'
  patch 'menus/:id', to: 'menus#update', as: 'update_menu'

  resources :customers
  get 'customers', to: 'customers#index'
  get 'customers/new', to: 'customers#new'
  post 'customers', to: 'customers#create'
  delete 'customers/:id', to: 'customers#destroy'
  get 'customers/:id', to: 'customers#show'
  get 'customers/:id/edit', to: 'customers#edit'
  patch 'customers/:id', to: 'customers#update', as: 'update_customers'

  resources :orders
  get 'orders', to: 'orders#index'
  get 'orders/new', to: 'orders#new'
  get 'orders/new/:id', to: 'orders#new_by_customer', as: 'get_order_customer'
  post 'orders/:id', to: 'orders#create'
  delete 'orders/:id', to: 'orders#destroy'
  get 'orders/:id', to: 'orders#show'
  get 'orders/:id/edit', to: 'orders#edit'
  patch 'orders/:id', to: 'orders#update', as: 'update_orders'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :menus
    validates :name, presence: true, uniqueness: {
        message: "is already taken"
      }

  def render_name
    "#{name}"
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def index
    if params[:search].nil?
      @categories = Category.all
    else
      @parameter = params[:search].downcase  
      @categories = Category.where("lower(name) LIKE :search", search: "%#{@parameter}%")  
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to categories_path
    else
      flash[:error] = @category.errors.full_messages.[](0)
      render :edit
    end
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category created successfully."
      redirect_to action: :index
    else
      flash[:error] = @category.errors.full_messages.[](0)
      render action: :new
    end
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<div class="border-2 border-gray-300 p-4 h-96">
<h1 class="text-2xl">Edit menu category</h1>
<hr class="mb-4" />
<%= form_with model: Category.new, url: update_category_url(@category), class: 'flex flex-col', method: :patch do |form| %>
    <div>
  <%= form.label :name, "Category Name:" %>
  <%= form.text_field :name, value: @category.name, class: 'border-2 border-gray-200 rounded-md focus:ring-2 focus:ring-blue-600 w-full mt-4 h-8 px-2' %>
  <p class="mt-4 text-red-600"><%= flash[:error] %></p>
  </div>
  <div class="flex flex-row self-end mt-16">
  <%= link_to "Cancel", :categories, class: "bg-gray-400 text-white p-2 rounded-md" %>
  <%= form.submit "Submit Category", class: 'bg-green-500 active:bg-green-700 cursor-pointer text-white p-2 rounded-md ml-4' %>
  </div>
<% end %>
</div>

app/views/categories/index.html.erb
<div class="flex flex-row justify-between items-center">
<h1 class="text-xl font-bold">Food Categories</h1>
  <%= link_to "Add Category", :categories_new, class: "bg-blue-500 text-white mb-2 p-2 rounded-md" %>
</div>

<%= form_with url: "/categories",  class: 'mb-4', method: :get do |form| %>
  <%= form.label :search, "Search for:" %>
  <%= form.text_field :search, class: 'border-2 border-gray-200 rounded-md focus:ring-2 focus:ring-blue-600 w-full my-4 h-8 px-2' %>
  <%= form.submit "Search", class: 'bg-green-500 active:bg-green-700 cursor-pointer text-white p-2 rounded-md'%>
<% end %>

<table class="table-fixed w-full">
  <thead>
    <tr>
      <th class="w-1/12 border-gray-400 border-2">No</th>
      <th class="w-1/2 border-gray-400 border-2">Category Name</th>
      <th class="w-1/4 border-gray-400 border-2">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each.with_index do |category, index| %>
      <tr>
        <td class="border-gray-400 border-2 text-center"><%= index + 1 %></td>
        <td class="border-gray-400 border-2 px-2"><%= category.name %></td>
        <td class="border-gray-400 border-r-2 border-b-2 flex flex-col px-32">
            <%= link_to "View",  category_path(category, @category) , class: "bg-green-500 text-white mt-2 mb-2 p-2 rounded-md text-center" %>
            <%= link_to "Edit",  edit_category_path(category, @category), class: "bg-blue-500 text-white mt-2 mb-2 p-2 rounded-md text-center" %>
            <%= link_to "Delete",  category_path(category, @category), method: :delete, class: "bg-red-500 text-white mt-2 mb-2 p-2 rounded-md text-center" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<div class="border-2 border-gray-300 p-4 h-96">
<h1 class="text-2xl">Add menu categories</h1>
<hr class="mb-4" />
<%= form_with model: Category.new, url: "/categories", class: 'flex flex-col', method: :post do |form| %>
    <div>
  <%= form.label :name, "Category Name:" %>
  <%= form.text_field :name, class: 'border-2 border-gray-200 rounded-md focus:ring-2 focus:ring-blue-600 w-full mt-4 h-8 px-2' %>
  <p class="mt-4 text-red-600"><%= flash[:error] %></p>
  </div>
  <div class="flex flex-row self-end mt-16">
  <%= link_to "Cancel", :categories, class: "bg-gray-400 text-white p-2 rounded-md" %>
  <%= form.submit "Submit Category", class: 'bg-green-500 active:bg-green-700 cursor-pointer text-white p-2 rounded-md ml-4' %>
  </div>
<% end %>
</div>

app/views/categories/show.html.erb
<div class="border-2 border-gray-300 p-4 h-96">
<div class="flex flex-row justify-between">
<h1 class="text-2xl">Category Name</h1>
<%= link_to "Back", :categories, class: "bg-gray-400 text-white p-2 rounded-md" %>
</div>
<hr class="mb-4" />
<%= form_with class: 'flex flex-col' do |form| %>
    <div>
  <%= form.label :name, "Category Name:" %>
  <%= form.text_field :name, value: @category.name, :disabled => true, class: 'disabled:bg-gray-400 border-2 border-gray-200 rounded-md focus:ring-2 focus:ring-blue-600 w-full mt-4 h-8 px-2' %>
  </div>
  <div class="flex flex-row self-end mt-16">
  <%= link_to "Delete", category_path(@category), method: :delete, class: "bg-red-500 text-white p-2 rounded-md" %>
  <%= link_to "Edit", edit_category_path(@category), class: "w-16 bg-blue-500 text-white p-2 rounded-md ml-4 text-center" %>
  </div>
<% end %>
</div>